const areadata = [
    { key: 'beiJing', name: '北京', projectNum: 81, objectNum: 12003 },
    { key: 'shangHai', name: '上海', projectNum: 70, objectNum: 10562 },
    { key: 'tianJin', name: '天津', projectNum: 66, objectNum: 8693 },
    { key: 'chongQin', name: '重庆', projectNum: 68, objectNum: 8500 },
    { key: 'guangDong', name: '广东', projectNum: 92, objectNum: 14530 },
    { key: 'zheJiang', name: '浙江', projectNum: 88, objectNum: 12003 },
    { key: 'jiangSu', name: '江苏', projectNum: 82, objectNum: 10302 },
    { key: 'siChuan', name: '四川', projectNum: 76, objectNum: 10065 },
    { key: 'heBei', name: '河北', projectNum: 70, objectNum: 11032 },
    { key: 'shanXi', name: '山西', projectNum: 65, objectNum: 8700 },
    { key: 'liaoNing', name: '辽宁', projectNum: 56, objectNum: 7603 },
    { key: 'jiLin', name: '吉林', projectNum: 52, objectNum: 6847 },
    { key: 'heiLongJiang', name: '黑龙江', projectNum: 51, objectNum: 6953 },
    { key: 'anHui', name: '安徽', projectNum: 61, objectNum: 6584 },
    { key: 'fuJian', name: '福建', projectNum: 72, objectNum: 8937 },
    { key: 'jiangXi', name: '江西', projectNum: 50, objectNum: 6701 },
    { key: 'shanDong', name: '山东', projectNum: 72, objectNum: 8405 },
    { key: 'heNan', name: '河南', projectNum: 78, objectNum: 9547 },
    { key: 'huBei', name: '湖北', projectNum: 65, objectNum: 8097 },
    { key: 'huNan', name: '湖南', projectNum: 62, objectNum: 8003 },
    { key: 'haiNan', name: '海南', projectNum: 42, objectNum: 6780 },
    { key: 'guiZhou', name: '贵州', projectNum: 32, objectNum: 4981 },
    { key: 'yunNan', name: '云南', projectNum: 31, objectNum: 4532 },
    { key: 'shanXiS', name: '陕西', projectNum: 45, objectNum: 6983 },
    { key: 'ganSu', name: '甘肃', projectNum: 42, objectNum: 5872 },
    { key: 'qingHai', name: '青海', projectNum: 23, objectNum: 4503 },
    { key: 'neiMengGu', name: '内蒙古', projectNum: 21, objectNum: 4203 },
    { key: 'guangXi', name: '广西', projectNum: 56, objectNum: 7892 },
    { key: 'ningXia', name: '宁夏', projectNum: 31, objectNum: 5610 },
    { key: 'xinJiang', name: '新疆', projectNum: 21, objectNum: 4031 },
    { key: 'xiZang', name: '西藏', projectNum: 19, objectNum: 2933 },
    { key: 'tiWan', name: '台湾', projectNum: 10, objectNum: 2010 }
  ]

  export default areadata;
